# require 'byebug'

# debugger

def calcula_soma
    a = 1 + 1

    return 1

    a += 2

   return a
end

puts calcula_soma

jkhjkhjjçlkçlkçlklçkçlkçlkoipopoipoiopyuiyiuyuiyttyrtyrtyhghhgfhccbcbmnbnmkkkjiyiuyhjkhjkljuiouoiljklnm,,jkffhvcvbdgfddretfgdfgdggjhgjgjhgjjhgjhgjhgjhgjhgjhgjhgjhgjhgjhgjhjhgjhjhjhgjhgjhgjhgjhgjhgjhgjgjhgjhjhjhgjhjhgjhjhjjhgjhgjhgjjgjhjhjhjhjhgjhjhgjhjhjhgjhjhgjhgjjhjhjhgjhjhjhgjhgjhjhgjhgjhgjhgjhgjhjhjhgjhjhjhgjhgjhgjhjhjhjhjhjhgjhgjhgjhgjhjhgjhjhgjhjhjhgjhjhgjhgjhjhgjhhjggjgjhkhkjhjkhkhkjkjkkjkkkkkkhkjhkjhkjlkjlkjkljlklklçkçlklççllloiçjkjlklggjhgjhgjkljlçloṕpópóiuyoiuoiuuyyujhgjhfhfhhbnvnmbmn,mm.çjkljoiuiouuyyuiggjhyujhgjvbmbmm,,,mlkjlkkjkljkljlkjlklkkllklljllljljllklkjljllçkçlkçlçkçl

